# Pull base image.
FROM node:4.5.0

# Install Bower & Gulp
RUN npm install -g bower gulp nightwatch

# Define working directory.
WORKDIR /app

# Define default command for us to overwrite
CMD ["bash"]